

using System.Collections.Generic;
using System;
using System.Linq;

// 시작
Test.Run(new Solution().solution, new TestCase[]
{
    new(2, 3, new int[,] { { 1, 1, 0 }, { 1, 1, 0 }, { 0, 0, 1 } }),
    new(1, 3, new int[,] { { 1, 1, 0 }, { 1, 1, 1 }, { 0, 1, 1 } }),
    new(1, 4, new int[,] { { 1, 0, 1, 0 }, { 0, 1, 1, 1 }, { 1, 1, 1, 1 }, { 0, 1, 1, 1 } }),
    Generation.New(),
    Generation.New(),
    Generation.New(),
    Generation.New(),
    Generation.New(),
    Generation.New(),
    Generation.New(),
    Generation.New(),
    Generation.New(),
    Generation.New(),
    Generation.New(),
    Generation.New(),
    Generation.New(),
    Generation.New(),
    Generation.New(),
    Generation.New(),
    Generation.New(),
    Generation.New(),
    Generation.New(),
    Generation.New(),
    Generation.New(),
    Generation.New(),
    Generation.New(),
    Generation.New(),
    Generation.New(),
    Generation.New(),
    Generation.New(),
    Generation.New(),
    Generation.New(),
    Generation.New(),
    Generation.New(),
    Generation.New(),
    Generation.New(),
    Generation.New(),
    Generation.New(),
    Generation.New(),
    Generation.New(),
    Generation.New(),
    Generation.New(),
    Generation.New(),
    Generation.New(),
    Generation.New(),
    Generation.New(),
    Generation.New(),
    Generation.New(),
    Generation.New(),
    Generation.New(),
    Generation.New(),
});
